// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdrDsGy6tFjyasjNhRhsdougzMkoLTgUE',
    appId: '1:441014532620:web:d37ea8deab2d365cb5cc29',
    messagingSenderId: '441014532620',
    projectId: 'smart-health-tracker-e4033',
    authDomain: 'smart-health-tracker-e4033.firebaseapp.com',
    storageBucket: 'smart-health-tracker-e4033.firebasestorage.app',
    measurementId: 'G-5VDY8VXWXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoXNRW_SoLd9k8eymSuswQ-P9ws8m1eN4',
    appId: '1:441014532620:android:9c04506a9319f6abb5cc29',
    messagingSenderId: '441014532620',
    projectId: 'smart-health-tracker-e4033',
    storageBucket: 'smart-health-tracker-e4033.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0X76AmdXzY8K0cqFUaSX0BgPwGl5ii1U',
    appId: '1:441014532620:ios:28db163dbc0df0a1b5cc29',
    messagingSenderId: '441014532620',
    projectId: 'smart-health-tracker-e4033',
    storageBucket: 'smart-health-tracker-e4033.firebasestorage.app',
    iosBundleId: 'com.example.gsocSmartHealthReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0X76AmdXzY8K0cqFUaSX0BgPwGl5ii1U',
    appId: '1:441014532620:ios:28db163dbc0df0a1b5cc29',
    messagingSenderId: '441014532620',
    projectId: 'smart-health-tracker-e4033',
    storageBucket: 'smart-health-tracker-e4033.firebasestorage.app',
    iosBundleId: 'com.example.gsocSmartHealthReminder',
  );
}
